version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todos-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - todo-network
    environment:
      DB_URL: jdbc:mysql://mysql:3306/todo
      DB_USER: root
      DB_PASSWORD: root

networks:
  todo-network:
    driver: bridge
